'use strict';
var Language = window.Language || {};
Language.STRINGS = Language.STRINGS || {};
Language.STRINGS['en'] = {
    'lan_select0': 'English',
    'lan_select1': 'Chinese',
    'home': 'HOME',
    'cv': 'RESUME',
    'projects': "PROJECTS",
    'contacts': "CONTACTS",
    'hello': "HELLO",
    'home_avail': "I'm available for work.",
    'home_self': "I'm a software developer who is passionate about technology and business.I love to program not only to create code, but to create value.",
    'home_af': 'Available for:',
    'home_wd': "Web Developer",
    'home_jd': "Java Developer",
    'home_sd': "Software Developer",
    'home_fs': "Full Stack",
    'home_ws': "Website:",
    'home_dh': "Cell:",
    'home_yx': "Email:",
    'home_sj': "Social links:",
    'home_cv': "RESUME",
    'home_st': "STRENGTHS",
    'home_stc': "Motivation, adaptable, creative, quick learner and working under pressure",
    'home_qt': "FAVORITE QUOTE",
    'home_qtc': "Time is like the water in sponge: if you squeeze, you can always get some.",
    'home_rp': "RECENT PROJECT",
    'home_rpc': "Build a next generation online banking site using emberJs",
    'contacts_look': "Looking forward to answering your email.",
    'contacts_name': "Name",
    'contacts_email': "Email",
    'contacts_subject': "Subject",
    'contacts_message': "Message",
    'contacts_send': "Send",
    'contacts_con': "CONTACT",
    "project_break": "Breakout",
    "project_bank": "Bank Application",
    "project_pw": "Personal Website",
    "project_demo": "Demo",
    "project_code": "Code",
    "download": "Download",


};